### ISSUE TITLE
나는 이걸 건드린 적이 없는데..ㅇㅅaㅇ

### ISSUE THREAD

**Issue by ho-hwa** [oneandzeroteam/cs50#11]
Traceback (most recent call last):
  File "./tweets", line 3, in <module>
    from helpers import get_user_timeline
  File "/home/ubuntu/workspace/sentiments/helpers.py", line 3, in <module>
    import plotly
ImportError: No module named 'plotly'

**Comment by nicholaskim94** [comment]
ploty라는 모듈이 없다는건데요, `pip install plotly`로 plotly 모듈을 설치해보시기 바랍니다
